### ISSUE TITLE
API not functional for sequence data

### ISSUE THREAD

**Issue by ursueugen** [sfu-ireceptor/API#7]
Hi,

So I want to download public iReceptor sequence data. 
I consulted the API in the repo, but the base url seems to be unfunctional:
```
$ curl -X GET "https://ipa.ireceptor.org/v2"
curl: (7) Failed to connect to ipa.ireceptor.org port 443: No route to host
```

I found in iReceptor docs (http://ireceptor.irmacs.sfu.ca/node/112) another base url which I tried to use: https://ipa1.ireceptor.org/v2/
```
$ curl -X GET "https://ipa1.ireceptor.org/v2/"
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://ipa1.ireceptor.org/v2">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at ipa1.ireceptor.org Port 443</address>
</body></html>
(base) 
```
Although get a response for clonotype summary:
```
curl -X GET "https://ipa1.ireceptor.org/v2/sequences_summary"
```

I don't get a response for API requests with other parameters, e.g. sequence data for samples, responds with "Page not found":
```
curl -X GET "https://ipa1.ireceptor.org/v2/sequences_summary?ir_project_sample_id_list=A3wk2,A4pre"
```

Could you suggest the right steps to download sequence data according to the appropriate unique identifier (I assume sample ID, although some samples don't have sample ID)?

Thanks

**Comment by bcorrie** [comment]
Hello,

Sorry for the slow reply...

Because almost all API calls to the IPA repositories come from the iReceptor Gateway, we have not been keeping the API documentation up to date. It has changed a bit since the spec on the web, and our documentation needs some attention...

As we are about to move to using the new AIRR Community's AIRR Data Commons API (http://docs.airr-community.org/en/latest/api/adc_api.html) we would prefer to not "encourage" use of the old API as it will soon be deprecated. And we also don't want to spend time updating the old documentation. 

We are happy to help you in the short term with using the iReceptor API, but we will take that dialog off line...

I will close this issue, and discuss this in more detail in email...

Brian
